---
title: "R Notebook"
output: html_notebook
---

#Questions 1
```{r}
A <- matrix(c(5,-4,-1,1),2,2,TRUE)
b <- c(-10,2)
showEqn(A,b)
```
```{r}
Solve(A,b) #untuk mencari solusi SPL
```
```{r}
plotEqn(A,b) #visualisasi untuk SPL dengan 2 variabel
```
```{r}
echelon(A,b) #untuk mencari solusi dengan row-echelon
```
```{r}
echelon(A,b, verbose=TRUE) #untuk melihat operasi baris elementer
```
```{r}
echelon(A,b, verbose=TRUE, fraction=TRUE) #fraction untuk mengubah nilai yang desimal menjadi pecahan
```
#Questions 2
```{r}
B <- matrix(c(4,-2,0,5,-2,1,3,4,-1),3,3,TRUE)
c <- c(2,7,3)
showEqn(B,c)
```
```{r}
Solve(B,c)
```
```{r}
plotEqn3d(B,c) #untuk SPL dengan 3 variabel
```

```{r}
echelon(B,c)
```
```{r}
echelon(B,c, verbose=TRUE)
```
```{r}
echelon(B,c, verbose=TRUE,fraction=TRUE)
```
#Questions 3
```{r}
C <- matrix(c(1,1,1,2,3,5,4,0,5),3,3,TRUE)
d <- c(5,8,2)
showEqn(C,d)
```
```{r}
Solve(C,d)
```
```{r}
plotEqn3d(C,d)
```

```{r}
echelon(C,d)
```
```{r}
echelon(C,d, verbose=TRUE)
```
```{r}
echelon(C,d, verbose=TRUE, fraction=TRUE)
```
#Questions 4

```{r}
D <- matrix(c(2,5,1,-1,4,3,5,0,-2),3,3,TRUE)
e <- c(-12,-4,-13)
showEqn(D,e)
```
```{r}
Solve(D,e)
```
```{r}
plotEqn3d(D,e)
```

```{r}
echelon(D,e)
```
```{r}
echelon(D,e,verbose=TRUE)
```
```{r}
echelon(D,e, verbose=TRUE,fraction=TRUE)
```

